[alias]
test-all = "test --all-features --workspace"
fmt-all = "fmt --all"
clippy-all = "clippy --all-targets --all-features -- -D warnings"
doc-all = "doc --workspace --no-deps --all-features --document-private-items --examples"
